# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab253ad35cfe2eb624c420ace1b123f80ab12c185ff77c84eacbdca6cd97536dc12d7f41e4c15f475a8323e4bf26c10c2f1ac610f215d75f7c51059dd8472a15

test:
  secret_key_base: 71a54b265388a42caf8e7fa874984364873c8a6433d1a2ea6e67818ffc32a867f10d69e125f031596ea5af36a46eeb8006b6f62cc511eddbe3ec326ec1f40ae7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
